#! /usr/bin/env python
# -*- coding: utf-8 -*-

#This is the main file to launch the program

import os, datetime, time

try:
    # Try the non-PIP case.
    from el_ui import * # <- need to clean, dirty 
    from el_device import * # <- need to clean, dirty
    from el_input import *  # <- need to clean, dirty
    from el_parse import *  # <- need to clean, dirty
    from el_plot import *  # <- need to clean, dirty
except ImportError:
    # Maybe it's a PIP-installed package.
    from eltuxusb.el_ui import * # <- need to clean, dirty
    from eltuxusb.el_device import * # <- need to clean, dirty
    from eltuxusb.el_input import *  # <- need to clean, dirty
    from eltuxusb.el_parse import *  # <- need to clean, dirty
    from eltuxusb.el_plot import *  # <- need to clean, dirty
    import pkgutil
    glade_file = os.path.join(pkgutil.get_loader("eltuxusb").filename, glade_file)

#from time import localtime

pathname = os.path.dirname(sys.argv[0])
full_path = os.path.abspath(pathname)
os.chdir(full_path)

if __name__ == '__main__':
    app = eltuxusb().refresh()
    gtk.main()
